### ISSUE TITLE
Fix Bullet Hole 

### ISSUE THREAD

**Issue by Neeekoo-Chan** [MoeMod/CSMoE#101]
Just Like The Old One When You Use Shotgun The Bullet Hole In The Map Is Random

**Comment by MoeMod** [comment]
Can you provide with some screenshots? I am sorry that I don't really know what you refer to.

**Comment by Neeekoo-Chan** [comment]
![Screenshot_20190809-095129](https://user-images.githubusercontent.com/52073886/62748540-971d2180-ba8b-11e9-8dec-c92f173cfcd7.png)
This is from cs1.6client

**Comment by Neeekoo-Chan** [comment]
![Screenshot_20190809-094823](https://user-images.githubusercontent.com/52073886/62748573-b2882c80-ba8b-11e9-8245-5161361c78d9.png)
Then this is from csmoe

**Comment by MoeMod** [comment]
I dont know whether it is engine-related issue. I will check it later.

**Comment by MoeMod** [comment]
fixed
