### ISSUE TITLE
LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”

### ISSUE THREAD

**Issue by zanker35** [MoeMod/CSMoE#114]
1>------ 已启动生成: 项目: client, 配置: Debug x64 ------
1>LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”
1>已完成生成项目“client.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

我在vs2017编译client的时候出现的问题，而编译server就不会出现该问题，求助大佬，谢谢。

**Comment by MoeMod** [comment]
![image](https://user-images.githubusercontent.com/37328384/63780628-04013a00-c91b-11e9-9731-970c414c944d.png)
可以尝试把目标修改为v141_xp编译器和7.0 SDK

**Comment by zanker35** [comment]
> ![image](https://user-images.githubusercontent.com/37328384/63780628-04013a00-c91b-11e9-9731-970c414c944d.png)
> 可以尝试把目标修改为v141_xp编译器和7.0 SDK

感谢，想再询问一下，这个server和client直接编译用到普通版本的CS 3266之类的应该可以吧。

**Comment by MoeMod** [comment]
3266的client.dll是需要加密的应该不可以，但是steam版是可以的。不过这部分client里面缺少vgui2的内容，所以并不能像原版一样用。

**Comment by zanker35** [comment]
> 3266的client.dll是需要加密的应该不可以，但是steam版是可以的。不过这部分client里面缺少vgui2的内容，所以并不能像原版一样用。

好的，非常感谢。
