### ISSUE TITLE
The app wont install

### ISSUE THREAD

**Issue by AmpedgamR** [MoeMod/CSMoE#131]
I tried to install the pre-release of the app but it won't install.

**Comment by MoeMod** [comment]
The pre-release apk is unsigned. You may either turn off validation or sign the apk by yourself.

**Comment by AmpedgamR** [comment]
How.

**Comment by AmpedgamR** [comment]
I'm sorry I think it's because I have a Android phone that is an 5.1.

**Comment by MoeMod** [comment]
the continuous build is for arm64 only. 32bit devices are not supported.

**Comment by AmpedgamR** [comment]
Moe I figured out an app for 32 bit devices . I'm sorry I messed with your apt though but I can send it to you.

**Comment by AmpedgamR** [comment]
But it's not finished has errors

**Comment by AmpedgamR** [comment]
Hi I made an apk for 32bit devices. Also where is the data for csmoe for the latest version of the build?

**Comment by MoeMod** [comment]
> Hi I made an apk for 32bit devices. Also where is the data for csmoe for the latest version of the build?

https://github.com/MoeMod/CSMoE-GameDir
Maybe we should pack resources into apk somehow...

**Comment by AmpedgamR** [comment]
There's one way.

**Comment by MoeMod** [comment]
done
