### ISSUE TITLE
half life and csmoe

### ISSUE THREAD

**Issue by lev24197** [MoeMod/CSMoE#144]
Can you create new csmoe with monster in halflife and spawn it

**Comment by MoeMod** [comment]
I am afraid I cant. The monsters are using ZBOT's navigation system, which is not present in half-life.

**Comment by lev24197** [comment]
Yeah

**Comment by lev24197** [comment]
Where picture zombie near skill zombie

**Comment by MoeMod** [comment]
won't fix
