### ISSUE TITLE
App not install

### ISSUE THREAD

**Issue by neko-chan27** [MoeMod/CSMoE#155]
Can you create the apk of a latest version on your game with signed and support 32bit i play this before but because of the update i cant play this anymore i really really want to play your work so please create app that can support 32bit with signed apk

**Comment by HowToDoThis** [comment]
Due some reason we don't have any signature signs so we can't make a signed application files to anyone, but you can signed by your self

**Comment by neko-chan27** [comment]
But how ? Im sorry im not very so good to this problem

**Comment by HowToDoThis** [comment]
are you building your self or using the continuous tag build?

**Comment by HowToDoThis** [comment]
rightnow we will try using sign tool and build a signed apk, but dunno when we can done it, stay tuned

**Comment by woshihuange1** [comment]
> 由于某些原因，我们没有任何签名，因此我们无法将签名的应用程序文件提供给任何人，但是您可以自行签名

How to sign? I can't download apk, so what signature can I use?

**Comment by MoeMod** [comment]
fixed in v22-citrus
