### ISSUE TITLE
Skybox in zombie mode

### ISSUE THREAD

**Issue by sledgehammer0019** [MoeMod/CSMoE#157]
Can we disable the "night" skybox when playing zombie mode?? Some maps are dark and it even makes the map darker.. how to disable it?

**Comment by Thienannguyen123** [comment]
you can setting your sky by find word have name is hk

**Comment by sledgehammer0019** [comment]
> you can setting your sky by find word have name is hk

what do you mean??? where could I find it? on what file?

**Comment by Thienannguyen123** [comment]
GFX/Env and find the word hk 
ps:if you want to use custom sky you need to rename it 
ex:sunup-->hkup

**Comment by sledgehammer0019** [comment]
After finding it, what will I do? Can I delete it to just use the default skybox of a map I'm playing? Or just replace it?

**Comment by Thienannguyen123** [comment]
delete it will error 
so you just take some skybox in gamebanana and change to hk but don't delete 2 word last

**Comment by sledgehammer0019** [comment]
okay thank you!

**Comment by MoeMod** [comment]
Some specialized configs for each map should be introduced.
It seems that CSO already provided them in .nar .

**Comment by MoeMod** [comment]
fixed in v22-citrus
