### ISSUE TITLE
[Request] Change console text font

### ISSUE THREAD

**Issue by JusicP** [MoeMod/CSMoE#16]
From this:
![default](https://user-images.githubusercontent.com/25232950/44300880-9b9a7880-a316-11e8-88b5-ff5806147f52.png)
To like this:
![default](https://user-images.githubusercontent.com/25232950/44300889-bb31a100-a316-11e8-9517-ef2a14c81451.png)

**Comment by JusicP** [comment]
I don't know where is console font located. Who knows?

**Comment by JusicP** [comment]
I found util for console font modify(makefont) but i can't choose the settings for font.

**Comment by MoeMod** [comment]
In Xash3D, the font is just CS 1.5 style.
The second one is CS 1.6 style. It may need vgui2, which is not implemented in Xash3D up to now.

**Comment by MoeMod** [comment]
#55 may helps.
Why not make a version with VGUI2 for PC ?

**Comment by MoeMod** [comment]
Closed. Feel free to open another issue if you have further questions!
