### ISSUE TITLE
Failing to add weapon plugins

### ISSUE THREAD

**Issue by Adnan1091** [MoeMod/CSMoE#187]
Hello,i am trying to add this weapon to csmoe https://gamebanana.com/gamefiles/10552 but csmoe does not see the weapon.It works on cs1.6 cilent tho.How can i make it seen?Also i want to restore shields in this game.How can i do it?

**Comment by Thienannguyen123** [comment]
Yo hey all of weapon in csmoe was release by coding and amxmodx don't support android so that your reason

**Comment by Adnan1091** [comment]
Then tell me at least how can i restore ballistic shield?

**Comment by Thienannguyen123** [comment]
In zombie mode you can't buy shield bút normal mode you can

**Comment by Adnan1091** [comment]
Nope,in both of the modes you cant buy the shield.I began to think you are talking about standard 1.6 cilent.

**Comment by MoeMod** [comment]
amxx is not implemented in xash3d. All weapons are hardcoded with C++.

**Comment by Adnan1091** [comment]
So,arent there any way to add these amxx weapons?Well,can you tell me how can i restore shields in csmoe as it isnt related to amxx?

**Comment by wolverine998** [comment]
Shield is already implemented in the game, you have to change the modstrategy so that the game gives the shields. Of course you need programming skills.

**Comment by dewaka131** [comment]
please radar 3d for all maps

**Comment by dewaka131** [comment]
and I need to add the Shotgun

**Comment by HowToDoThis** [comment]
Closing this issues due off it is not very helpful to devs or solved.
