### ISSUE TITLE
Nerf knockback dual phantom

### ISSUE THREAD

**Issue by Thienannguyen123** [MoeMod/CSMoE#188]
Can we nerf knockback dual phantom because it have a strong knock back that no zombie can touch to the people using dual phantom

**Comment by MoeMod** [comment]
It semms to be a bug that every knife can knockback zombie. will be fix when some new logic comes.

**Comment by Thienannguyen123** [comment]
Near 1 month, số why we don't have a big or small update @MoeMod

**Comment by Adnan1091** [comment]
2 months

**Comment by MoeMod** [comment]
fixed in v22-citrus
