### ISSUE TITLE
vehicles bug

### ISSUE THREAD

**Issue by Adnan1091** [MoeMod/CSMoE#190]
When you ride a vehicle,you wont be able to control it if you rotate it to left side.For example,your vehicle will still turn to left side if you rotated into the said side first.

**Comment by Adnan1091** [comment]
This is a bug report not a question.

**Comment by MoeMod** [comment]
Testd on map as_pursuit.bsp (func_vehicle), no bug found.

**Comment by Adnan1091** [comment]
[ScreenRecord-20200622-221241.zip](https://github.com/MoeMod/CSMoE/files/4815180/ScreenRecord-20200622-221241.zip)

**Comment by MoeMod** [comment]
I think that it's the same behavior on the original CS16-Client or steam CS.

**Comment by Adnan1091** [comment]
So this is a feature?Its very annoying if a map only depends on a vehicle...

**Comment by MoeMod** [comment]
cannot reproduce
