### ISSUE TITLE
Cannot see weapon model? HELP

### ISSUE THREAD

**Issue by wolverine998** [MoeMod/CSMoE#191]
I added new knife into the game. It works great expect that i can't see the model, it's not rendered or i dunno what happened. Do i need to convert models for mobile phone with an app?

**Comment by Thienannguyen123** [comment]
Yes , you do .-.

**Comment by wolverine998** [comment]
@Thienannguyen123 Dude stop posting comments that do not help or that are not understandable. I don't want to be rude, but ur not helping. Btw i fixed this, i forgot to add DefaultDeploy, and i didn't saw the model because i have removed TDeployDefault.

**Comment by Kuber001** [comment]
> @Thienannguyen123 Dude stop posting comments that do not help or that are not understandable. I don't want to be rude, but ur not helping. Btw i fixed this, i forgot to add DefaultDeploy, and i didn't saw the model because i have removed TDeployDefault.

How to add new weapon into the game?
