### ISSUE TITLE
I need help for buy menu,   Please

### ISSUE THREAD

**Issue by Medjed101** [MoeMod/CSMoE#194]
it may be a stupid question, but how did you make buy menu execute automatically at the start of each round?

**Comment by HowToDoThis** [comment]
Read more and research more this part, then you will know

**Comment by Medjed101** [comment]
I searched but could not find it,
if you could help me somehow I would be grateful

**Comment by HowToDoThis** [comment]
I had give a answer that can helps you find it. Just research more, read more, then you can know how game logics working. This is a basic of how game logics working, if still no idea, run through search through every files and read how he run game logics.

**Comment by Medjed101** [comment]
ok thank you
