### ISSUE TITLE
Shield is not selectable

### ISSUE THREAD

**Issue by Adnan1091** [MoeMod/CSMoE#196]
I know shields are removed because it is way too OP but make it selectable for players in bot matches.

**Comment by MoeMod** [comment]
It's already hardcoded removed because we can't make it work with new pistols and knives.

**Comment by Adnan1091** [comment]
Well,at least you could have put a warning instead of removing it because bots cant use new weapons.

**Comment by HowToDoThis** [comment]
welp, we're removed by hard way and we're using original resource files, so no fixes for this. Currently best solution is modify resource files by your self to kept this problem not occurs anymore.

**Comment by MoeMod** [comment]
it's buggy, and don't do that.
