### ISSUE TITLE
Some zombie scenerio issues

### ISSUE THREAD

**Issue by Adnan1091** [MoeMod/CSMoE#202]
1.Zombies are spawning at high frequency and it has no spawn limit.(I dont know if we can edit this in settings)
2.This game mode crashes in 1 minute even through a map has no zombie spawn points.
Also,why didnt you just brought zombies or other enemies from half life?You didn't need to make a new texture...

**Comment by HowToDoThis** [comment]
For 1&2, I think they noticed because long time ago they discussed about this problems.
Why they not using original HL models or textures its because this game are referencing a game called CSO (Steam CSN:S or CSN:Z by Nexon), a storyline mode. But not fully implement yet.

**Comment by MoeMod** [comment]
fixed in new v22-citrus
