### ISSUE TITLE
Windows QTLauncher not working 

### ISSUE THREAD

**Issue by avsar-master** [MoeMod/CSMoE#203]
when i start the launcher i get the following error;
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.

What is the reason?

**Comment by MoeMod** [comment]
It's not under construction any more. And it's not required to run this game.

**Comment by MoeMod** [comment]
You can build win32 or uwp version from source code, or just wait for the win32 CI.
