### ISSUE TITLE
New version bug feedback

### ISSUE THREAD

**Issue by hzd007** [MoeMod/CSMoE#21]
New version bug feedback:
1. Bullet holes will be arranged neatly.
2. the details page can not be clicked.
3. Although the zombie's blood volume is weakened, the zombie can still move forward after being shot. Except for the 1,000-blood zombies, the other parent zombies are still very tough. The zombie's blood volume is thick and only slightly slowed down after being shot. The reserve bullets are few. It is difficult for human beings to defend them when attacking the zombies and buying bullets. position
4. Teammate's head name will show through the wall, the position of the enemy can be seen in the personal decisive battle, I hope you can delete it
5. Zombie mode can only buy CT weapons. There are few weapons to choose from. I hope the author can repair it as soon as possible.
6. the BOT of the Second Bureau of the Zombie mode will unify the same CT camp role, which will result in aesthetic fatigue for a long time.
7.The new version doesn't seem to be able to search other CS1.6 servers, which makes it impossible for us to play with other players.
8.No sound was heard after killing one person: First kill, Crazy, Incredible, Excellent, etc.

**Comment by hzd007** [comment]
5, the new version does not seem to be able to search for other CS1.6 servers.

**Comment by MoeMod** [comment]
3. zombie knockback has already been added, but not released.
7. because the client is modified, it's not designed to work with CS1.6 servers.

**Comment by MoeMod** [comment]
4. It will be optimized soon. To disable it: cl_headname 0

**Comment by hzd007** [comment]
8.No sound was heard after killing one person: First kill, Crazy, Incredible, Excellent, etc.

**Comment by MoeMod** [comment]
In CSO there is also no sound after killing only one person.
These sound is triggered when you kill a lot in one round.

moved to #42
