### ISSUE TITLE
Windows UWP amd64 is  very problematic

### ISSUE THREAD

**Issue by avsar-master** [MoeMod/CSMoE#210]
I wondered about the new updates. I compiled the game but there are a lot of problems.

Windows 10 1909
![image](https://user-images.githubusercontent.com/61117050/85928269-636e0480-b8b4-11ea-9add-e35ec87dda09.png) - Bigger and bad quality huds

![image](https://user-images.githubusercontent.com/61117050/85928321-d6777b00-b8b4-11ea-9b6b-1cd588b0d2c3.png) - Big IMGUI console

![image](https://user-images.githubusercontent.com/61117050/85928410-64ebfc80-b8b5-11ea-80b6-49d53e1d26fa.png) - Mouse bug VGUI menu

**Comment by MoeMod** [comment]
It's win32 version but not UWP.
the scaling factor is calculated by hud_scale, and maybe there are some configs from other devices in your resource pack. Just delete *.cfg

**Comment by MoeMod** [comment]
mouse is not working if you switch to another window when loading. It should be fixed somewhen.

**Comment by MoeMod** [comment]
I have tested and the hud_scale calculation is wrong is win32 for sure.

**Comment by avsar-master** [comment]
Current version amd64. There was such a problem in the previous version. The problem is not gamedir.

**Comment by MoeMod** [comment]
The uwp version can be built with msvc/csmoe.sln, which should be not so buggy now.

**Comment by avsar-master** [comment]
so what is this vgui2_support

**Comment by MoeMod** [comment]
> so what is this vgui2_support

It's experimental and not used any more.
