### ISSUE TITLE
csmoe crash after opening.  my ARM IS ARM64-v8a plz fix this i've been waiting for this fix for 7 months plz add support for my type of device

### ISSUE THREAD

**Issue by XrazorXGaming** [MoeMod/CSMoE#214]
plz add more support for my type of device 
here's some cpu info
CPU Architecture: AArch64 Processor rev 4(aarch64)
Chipset:MT6753
Cores: 8
Instruction Sets:ARM64-v8a
CPU Features: fp asimd evtstrm aes pmull
                           sha1 sha2 crc32
CPU Governor: Interactive
Kernel Version: 3.18.19+
Kernel Architecture: aarch64
Render:MALI-T720
Vendor:Arm
OpenGL VERSION: OpenGL ES 3.0

**Comment by HowToDoThis** [comment]
Provide more message please. Make sure that read and followed the steps on README.md (since there are some platform not supporting)

**Comment by XrazorXGaming** [comment]
ok 
arigato gozaimas

**Comment by XrazorXGaming** [comment]
my device name is cherry mobile flares5

**Comment by XrazorXGaming** [comment]
i have a question when are you gonna start supporting more cpu's on android for this version of csmoe?

**Comment by MoeMod** [comment]
won't fix. 4GB RAM is required now
