### ISSUE TITLE
Updating the xash3d version

### ISSUE THREAD

**Issue by Adnan1091** [MoeMod/CSMoE#230]
Hello,do you have any plans for updating the xash3d version of this csmod?(like you are using 0.19.0 version and updating to stable0.20.0 or latest nighty build).

**Comment by MoeMod** [comment]
we have a lot of modifies on the original 0.19.3 version, or the latest on FWGS/xash3d repo. No plans are scheduled for upgrades.

**Comment by MoeMod** [comment]
won't fix
