### ISSUE TITLE
一些bug反馈

### ISSUE THREAD

**Issue by SuperRock2099** [MoeMod/CSMoE#24]
关于本体
7.部分枪支第一人称下无脚步声（未解决）
8.打在墙上的子弹孔会成几何矩阵排列（未解决）

关于生化模式
1.第二局开始角色就统一了
2.枪支仅限购买警用
4.装上bot radio声音文件后，僵尸也能说人话，也就是说生化bot和人类bot声音文件公用了
7.一些地图加载进去所有人出生点在同一位置

关于团战/个人战模式
1.自动添加bot人数不平衡（比如我设置bot quota为9，加完就变成我方4人，敌方6人，甚至全部加到敌方）
2.死亡后落地武器永远不会消失，堆积在地图中，影响帧率
3.团队模式计分板比分下方人数框边框消失只剩字
4.希望复活加入选枪界面，或者自动购买死前装备也行
5.希望加入复仇图标，增添快感

关于初始模式
1.爆破模式地图AB点弄反
2.非爆破地图中同样显示AB点，影响体验

————————分割线————————
在此表示对此作品的永远支持！

**Comment by MoeMod** [comment]
1. 各模式武器购买机制可能会修改为随机发枪，不需要再购买。因为现行Xash引擎不包括VGUI2模块，让程序生成购买菜单会非常麻烦所以暂时放弃了。
2. BOT人数建议在进入游戏之前的界面中设置，进游戏后应该不会错乱。
其他问题以后大概会修复的（

**Comment by MoeMod** [comment]
moved to #42
