### ISSUE TITLE
How to add or modify weapons in csmoe

### ISSUE THREAD

**Issue by anhhuy432** [MoeMod/CSMoE#250]
How to add or modify weapons in csmoe.  what tools are needed to do that

**Comment by Adnan1091** [comment]
@csmoe

**Comment by Adnan1091** [comment]
@moemod @justanoobqaq

**Comment by HowToDoThis** [comment]
Check [Building](https://github.com/MoeMod/CSMoE#building) to know how to develop on various platform.
Check PR to know more info on C++/C adding/creating weapons
Example: #235 #216 #215

**Comment by MoeMod** [comment]
no further question
