### ISSUE TITLE
About Project Status

### ISSUE THREAD

**Issue by HowToDoThis** [MoeMod/CSMoE#257]
We regret to inform you that, mostly our main maintenance or developers are busying on other projects and our own life, so we had no much times to devs on CSMoE. **We apologise for the inconvenience.**
So if there is any PR, I will review and approve it while I had notice or time.

**Comment by HowToDoThis** [comment]
Also an additional note for PR requester:
If PR didn't pass the build test, we will not merging on it.

**Comment by MoeMod** [comment]
won't fix. No more PR.
