### ISSUE TITLE
Update menu

### ISSUE THREAD

**Issue by mittorn** [MoeMod/CSMoE#27]
I have ported cs features to mainui_cpp in last update:
https://github.com/FWGS/mainui_cpp/tree/cs16client-1.34
It would be good to update menu here too

**Comment by MoeMod** [comment]
wow! Thanks for your impressive contributions.
I will try it. And we are looking for the ultimate mainui with vgui2!

**Comment by mittorn** [comment]
It is possible to write modern style ui with mainui_cpp
It have window system, item hoders. But scrolling items still not implemented.
You may try to port real vgui2, but it is not designed for touch. I think, writing vgui-style menu with mainui_cpp would be easier.

**Comment by MoeMod** [comment]
In addition, the current 'touch'-based Client GUI is still buggy... especially when we changed to another window and then the mouse/trackpad is no longer working.
Maybe CS16-Client is not designed to work in Windows/macOS/Linux, however everything except that is all-right.

**Comment by mittorn** [comment]
@MoeMod It is possible to make touch menus to work with dpad (by adding states for each item selected)
But of cause cpp implementation would be better. Touch controls was written for user customization, but in 2015 it was fastest way to create graphical menu. Old mainui code was very ugly and it's hard to modify/extend it, so we had no alternative

**Comment by MoeMod** [comment]
@mittorn 
The touch menu is good enough for static menus, but not some dynamically generated buy menus with weapon presets saving.
@a1batross 
The original CSBTE PC version comes with full VGUI2-based GameUI and Client Viewport but the new mobile version's UX is not as good for the PC one, and that is what players complain about.
In fact, I have planned to make another client for PCs with Viewport and VGUI2 menus. If the new mainui works, I would appreciate it for the simplified solution.

**Comment by mittorn** [comment]
@MoeMod 
https://github.com/FWGS/mainui_cpp/blob/a931d92fd024e1b765918932cb81c6766a3b8f8a/menus/Zoo.cpp
vgui2 schemes is supported. Try this

**Comment by a1batross** [comment]
There is no open-source VGUI2 implementation, except that's was leaked with Source Engine.

mainui_cpp can handle VGUI2 schemes, but it's incomplete. Parser is ready, but you need to override KeyValue() method in CMenuBaseItem derived classes. 

Also, Xash3D doesn't support VGUI2 and me or Unkle Mike have no plans to support it.

**Comment by mittorn** [comment]
@NOPEMS
For console, utf-8 and some codepages supported, but console uses single-byte font
con_charset may be cp1251 and cp1252 when cl_charset utf-8 selected
Menu now only supports english and cyrillic range. But you may try add others. We have not tested this.
We plan to implement language selection and maybe dynamic glyph loading

**Comment by NOPEMS** [comment]
@mittorn 
I mean the font of console string like deathmsg 
![font](https://user-images.githubusercontent.com/18642603/48242857-1657c900-e418-11e8-8a83-cc0fcff6ba73.JPG)
and [cl_charset], I have tried it, but it doesn't work.

**Comment by mittorn** [comment]
cl_charset must be utf-8, it is coding of strings in engine
con_charset is charset for engine font renderer which uses fonts.wad now and supports only cp1251 and cp1252

**Comment by MoeMod** [comment]
already done.
