### ISSUE TITLE
新增一個支持arm-v7a的裝置apk

### ISSUE THREAD

**Issue by gtab8025017** [MoeMod/CSMoE#271]
可以为我做一个相容arm-v7a装置的吗？别一直做arm64的apk好吗？
Can you make an arm-v7a compatible device for me?  Don't keep doing arm64 apk, okay

**Comment by MoeMod** [comment]
抱歉我们决定暂不构建armv7版本了。大概有以下方面的原因：
1. 5年内生产的智能手机都是64位的，目前32位设备现在的比重特别小
2. Android 12 将放弃32位程序支持
3. 新的lua功能在技术上大概率不支持32位

**Comment by gtab8025017** [comment]
可是我的手機是32位元的 並且安卓10 同一個apk應該可以增加好幾個cpu 吧！ Arm-v7a arm-v8a可以同時加到apk裡面嗎？求你做個arm-v7a的版本拜託～

**Comment by MoeMod** [comment]
luajit doesnt support 32bit.
