### ISSUE TITLE
Problem complie in android studio

### ISSUE THREAD

**Issue by carl1234a** [MoeMod/CSMoE#272]
I install android Sdk ndk and cmake but it's say you need to install cmake 3.19 and i have cmake 3.10 how to install it and path it to android studio

**Comment by MoeMod** [comment]
Bundled cmake 3.10.2.4988404 is ok for Android.
In addition, Android Studio provides with newer cmake 3.18.1 and you can try that.

**Comment by carl1234a** [comment]
But how to download lasted version cmake for android studio

**Comment by carl1234a** [comment]
Hey

**Comment by carl1234a** [comment]
Plz

**Comment by carl1234a** [comment]
Ok i fix it but it's say failure: build faibled with an exception
What went wrong 
......

**Comment by MoeMod** [comment]
no further question
