### ISSUE TITLE
CSMoE v22#265 一些bug

### ISSUE THREAD

**Issue by MoEPlayer-china** [MoeMod/CSMoE#274]
您好，我在游玩CSMoE v22#265时遇到一些问题。1.在安卓设备上，使用导航键返回游戏会闪退。2.CSMoE的垂直同步不知为什么无法关闭，希望可以将它关闭。3.希望可以做一个开关，来开关侧边换枪。4.在手机设备上的柑橘CSMoE无法显示完全的英文hud，中文是可以完全显示的

**Comment by MoEPlayer-china** [comment]
![Screenshot_20210413_081816](https://user-images.githubusercontent.com/82406715/114478520-f252d000-9bed-11eb-9a8e-a191b2496b3f.jpg)
显示不完整的英文hud
![Uploading Screenshot_20210413_082049.jpg…]()
正常显示的英文hud

**Comment by Otabek-Rizayev** [comment]
Bro how to install csmoe. I can't install it. My phone is arm64 android9. Please help me. I can't find it anywere how to install it.
Bro write me telegram: @idealdk

**Comment by MoEPlayer-china** [comment]
@Otabek-Rizayev Hey, brother, I hope I can help you. My device is arm64-v8a Android 11, but I can install csmoe. Maybe you need to sign the package name for APK

**Comment by Otabek-Rizayev** [comment]
> @Otabek-Rizayev @idealdk Hey, bro, I hope I can help you. My device is arm64-v8a Android 11, but I can install csmoe. Maybe you need to sign the package name for APK

please help me if you know this

**Comment by MoEPlayer-china** [comment]
@Otabek-Rizayev Csmoe's APK is not signed. You need to use software to sign it. In our Chinese player community, we often use MT file manager to sign APK

**Comment by Adnan1091** [comment]
How you managed to install amx plugins on android?

**Comment by Otabek-Rizayev** [comment]
> @Otabek-Rizayev Csmoe's APK is not signed. You need to use software to sign it. In our Chinese player community, we often use MT file manager to sign APK

Which app can I use in the play market?

**Comment by MoeMod** [comment]
fixed in v22-citrus
