### ISSUE TITLE
Drop UWP support

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#276]
Currently luajit doesn't support uwp.
Moreover, it seems that nobody is still using uwp in 2021, including Microsoft's first-party softwares.

**Comment by Qiangong2** [comment]
I'd like to use the UWP version since I'm using a Surface 2 RT on win 10 arm

**Comment by Kuber001** [comment]
What can I do to make the app run correctly? My device is an iPhone 10R
<img width="896" alt="Screenshot" src="https://user-images.githubusercontent.com/44465332/117537527-f91d0900-b01a-11eb-967d-784c0a976b6b.png">

**Comment by Kuber001** [comment]
Here you can write questions not related to the author's question?

**Comment by MoeMod** [comment]
done.
All 32bit version were dropped, and so was UWP armv7.
