### ISSUE TITLE
软件图标

### ISSUE THREAD

**Issue by SuperRock2099** [MoeMod/CSMoE#28]
链接：https://pan.baidu.com/s/1JCCHuZCY1meU_ohlsqC_uA 
提取码：f3xh 
给你做了一个app图标，还望笑纳

**Comment by NOPEMS** [comment]
开发者:不符合Android图标设计规范 
Android要求圆形背景
iOS要求方形背景
Windows/linux/Mac要求无背景

**Comment by MoeMod** [comment]
可以的话请提供PSD格式的图片吧。
但是...个人认为这个图标和原版CS16Client重合度很大，希望有一款能更衬托出CSMoE游戏设定的设计什么的，比如僵尸头像（笑）

**Comment by MoeMod** [comment]
#56 
closed.
