### ISSUE TITLE
android arm support (not arm64)

### ISSUE THREAD

**Issue by ahmad12331233** [MoeMod/CSMoE#280]
hello!! i have j2 prime phone and it dont support arm64 apps and the last android arm (not 64) was in v21-lcsm and the file name is CSMoE-v21-lcsm-Android.apk

just what i need is support android arm (not 64) again in the new versions like v22-hy and feature versions because the most android phones and tablets using the original arm and not arm64

**Comment by ahmad12331233** [comment]
and another thing in my grand prime phone android version 6.0 i got package error its doesn't install and in j2 prime with android 7.1 the app installs fine but doesn't work because j2prime cpu is arm (NOT arm64)

**Comment by ahmad12331233** [comment]
and the thing is xash 3d fwgs and csmoe v21 support android 4.4 and original arm but this new release (v22) just have android arm64 WHY i will switch back to cs 1.6 client if this didnt fixed

**Comment by Sergii03** [comment]
You have armeabi-v7a?

**Comment by MoeMod** [comment]
won't fix.
