### ISSUE TITLE
How to disable swiping weapon select? Please answer 

### ISSUE THREAD

**Issue by David770725** [MoeMod/CSMoE#281]

**Comment by ahmad12331233** [comment]
maybe you cant because they are edited the engine you can just change the button position if you cant press the buttons

**Comment by MoEPlayer-china** [comment]
@ahmad12331233

Developers are working to solve this problem in source code by making a switch or removing the entire moetouch-related code

**Comment by ahmad12331233** [comment]
oh ok

**Comment by MoeMod** [comment]
fixed in v22-citrus
