### ISSUE TITLE
i will switch back to cs 1.6 client if this didn't fixed

### ISSUE THREAD

**Issue by ahmad12331233** [MoeMod/CSMoE#282]
i have j2 prime phone and it dont support arm64 apps and the last android arm (not 64) was in v21-lcsm and the file name is CSMoE-v21-lcsm-Android.apk

just what i need is support android arm (not 64) again in the new versions like v22-hy and feature versions because the most android phones and tablets using the original arm and not arm64

and another thing in my grand prime phone android version 6.0 i got package error its doesn't install and in j2 prime with android 7.1 the app installs fine but doesn't work because j2prime cpu is arm (NOT arm64)

and the thing is xash 3d fwgs and csmoe v21 support android 4.4 and original arm but this new release (v22) just have android arm64 WHY i will switch back to cs 1.6 client if this didnt fixed

**Comment by ahmad12331233** [comment]
and when i used csmoe v22-hy ### **_on my pc_** there's an giant bug its the new console window , i cant type any command or anything

**Comment by ahmad12331233** [comment]
yes its another big buggy xash 3d project

**Comment by djgerman10** [comment]
xash3d brings news (BETA)  [xash3d-deploy](https://github.com/FWGS/xash3d-deploy/tree/anewengine-master)

**Comment by MoeMod** [comment]
won't fix. 4GB RAM is required.
