### ISSUE TITLE
Error complie it to android

### ISSUE THREAD

**Issue by carl1234a** [MoeMod/CSMoE#286]
I have launch project csmoe android in android studio but the building is not working

#
[log.txt](https://github.com/MoeMod/CSMoE/files/6345585/log.txt)

How to fix it plz 😓

**Comment by MoeMod** [comment]
Are you using the latest Android Studio? It's recommanded with 4.0+

**Comment by MoeMod** [comment]
duplicated #287

**Comment by MoeMod** [comment]
no further question
