### ISSUE TITLE
Error include could not find load files

### ISSUE THREAD

**Issue by carl1234a** [MoeMod/CSMoE#287]
I run build it but it's say include could not find files
How to fix it plz

**Comment by MoeMod** [comment]
https://github.com/MoeMod/CSMoE/blob/699a35eef70437ffeaa97d1452372ab6da5e699a/.travis.yml#L169
I am sorry that some extra libraries are added without instructions... README will be updated soon.

**Comment by carl1234a** [comment]
Thank you , you are legend

**Comment by MoeMod** [comment]
In addition, we are using really modern C++17 now. Ensure that your compiler is MSVC 16.8+, GCC 9.3+, Xcode 11.3+

**Comment by carl1234a** [comment]
Thanks but i need only android

**Comment by carl1234a** [comment]
Hey

**Comment by carl1234a** [comment]
I have a another error

**Comment by carl1234a** [comment]
....Csmoe/3rdparty/name of" which is not an existing directory

**Comment by carl1234a** [comment]
Finally is working

**Comment by MoeMod** [comment]
fixed
