### ISSUE TITLE
The apk installation package for android seems to be faulty even though I edited it with "APK editor" still can't install

### ISSUE THREAD

**Issue by ngatnguuen** [MoeMod/CSMoE#291]

**Comment by JustaNOOBQAQ** [comment]
Same as you lol

**Comment by ahmad12331233** [comment]
that's because its not support arm v7 cpu and just works with android 7 and its unsigned.......yeah the developers for this mod are killing csmoe with tooooooooooooo many issues so.... i don't know if you have android phone just use cs 1.6 client until they fix that

**Comment by MoeMod** [comment]
v22-citrus apk is signed.
