### ISSUE TITLE
Rename to CSMoE

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#30]
Due to some copyright problems, we are going to rename this repo.
The new name will be CSMoE, which is the abbr of Counter-Strike Mobile-oriented Edition.
In addition, this repo will be no longer related to any CSBTE versions.

references:
https://tieba.baidu.com/p/6082303737

**Comment by sledgehammer0019** [comment]
any tutorial on how to run this game? it works on CSBTE version but the latest doesn't seem to work? how to run it?

**Comment by MoeMod** [comment]
> any tutorial on how to run this game? it works on CSBTE version but the latest doesn't seem to work? how to run it?

You need to change gamedir from csbtem to csmoe to run new version.
However, new version needs some extra resources which can be downloaded from
https://github.com/MoeMod/CSMoE-GameDir

**Comment by Adeadlyfart** [comment]
What is source code? Where do I put this? Why I can't get any special weapon. Why this so hard

**Comment by MoeMod** [comment]
> What is source code? Where do I put this? Why I can't get any special weapon. Why this so hard

All this repo is source code. You can compile them.
Special weapons are just for testing and appropriate ways to get them are not available now.

**Comment by dewaka11** [comment]
please make me like a computer game blank point evolution 🙏 dan scope weapon mdl file

**Comment by HowToDoThis** [comment]
> please make me like a hud sprite game blank point evolution 🙏 dan scope weapon mdl file

This is not the right place that summit your request, open a new issues, wrote down your request, if your suggestion has noted by them, then they will implement for you. Here supposing used for discussing name related problems.

**Comment by J11789** [comment]
Can you add M3dragon.Infinity Fist.and x tracker plssss🙏🙏🙏🙏🙏🙏🙏🙏🙏
