### ISSUE TITLE
CSMoE v21 Above Doesn't Support 32-Bit Devices

### ISSUE THREAD

**Issue by noubiex** [MoeMod/CSMoE#308]
Why CSMoE v22-Citrus doesn't support 32-Bit Device😢😢?? I've Download the Latest apk and I Can't Install it , it says "Error on Parsing the Package" and appears with no icon in my file manager😢😢

**Comment by MoeMod** [comment]
Sorry that the new version requires 4GB RAM to run on Android. It can't run on any 32bit devices.

**Comment by noubiex** [comment]
Okay,❤❤thx for the info..Sadly I can't play it😔
