### ISSUE TITLE
Add battle royale mod :D

### ISSUE THREAD

**Issue by RomkaZVO** [MoeMod/CSMoE#31]
Please add this mode, because it is very popular. This should made your mod more famous in xash3d mobile community. We can also give you our map if it's needed.

**Comment by MoeMod** [comment]
It seems that xash3d engine cannot handle 100 players on a server. However, with just 32 players it's not fun enough. 
In addition, it needs lots of work to make zbot play with us...

All resources related are welcomed.

**Comment by mittorn** [comment]
You may use beams and radar for zone display (with special messages

Use this for distance visibility cut:
https://github.com/FWGS/hlsdk-xash3d/blob/gravgun/dlls/client.cpp#L1244
It will save fps and visents

**Comment by mittorn** [comment]
This to prevent sending too far sounds and effects
https://github.com/FWGS/hlsdk-xash3d/commit/4f2f31687934e11b1161ab4dbdfc7a51ee18d1ae#diff-4f976eee465508f18c9684a0a28ee0b5

**Comment by mittorn** [comment]
This code used on trash server in half-life to make server with 2000+ entities playable

**Comment by hadiasghari092** [comment]
when new version will be?

**Comment by Left4Dad** [comment]
So are you adding battle royale mod?? 32 players is already fun. Dangerzone supports 16 players and its fun! So plz add battle royale mod.

**Comment by MoeMod** [comment]
* Players can kill each other ignoring team (like DeathMatch), but cannot respawn
* Players cannot buy weapons and only get a knife after spawn
* Random weapon supplyboxes will appear on the map
* The one who survives wins the round

will be developed soon.

**Comment by Left4Dad** [comment]
Great!!!

**Comment by Left4Dad** [comment]
What is the expected date of the release??

**Comment by MoeMod** [comment]
won't fix. battle royale is somehow outdated now.
