### ISSUE TITLE
Don't build 64bit 

### ISSUE THREAD

**Issue by RomkaZVO** [MoeMod/CSMoE#32]
Terminal log https://pastebin.com/RHNK2D2N

**Comment by a1batross** [comment]
Modern C++ is conflicting with min/max defines. 

Either these macros should be avoided/renamed, either switch to plain C, where such macro is a normal practice.

**Comment by MoeMod** [comment]
This should be already fixed by public/minmax.h
I will try it again...

**Comment by MoeMod** [comment]
```
#include "port.h"
#include "minmix.h" // insert after port.h to redefine min and max
```
will helps...

**Comment by MoeMod** [comment]
I have tried 64bit bin can be built on all platforms ~~except Android~~.
However, it can be built on Android but doesn't work...

**Comment by MoeMod** [comment]
Recent version is checked on Ubuntu 19.04 with GCC 8.1
Those min/max issue should be already fixed.
