### ISSUE TITLE
Stay with C++11

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#35]
Since Xash3D is stuck in legacy GCC-based NDK, C++14 code CANNOT be compiled.
Tempory solution is continuing using C++11 standard.
It means the following feature is disabled:
1. make_unique
2. index_sequence
3. auto function return
4. advanced constexpr
5. varible template
6. exchange
...

**Comment by sledgehammer0019** [comment]
why does it have only 2 zombies? will all zombie types be implemented in the future?

**Comment by MoeMod** [comment]
> why does it have only 2 zombies? will all zombie types be implemented in the future?

Of course it will. However, we should implement the gameplay first.

**Comment by MoeMod** [comment]
v17 already fixed.
Hopes that it can be built on newer NDK soon.
