### ISSUE TITLE
Where is it??

### ISSUE THREAD

**Issue by choiminseongchoi** [MoeMod/CSMoE#36]
Where is the v16 game dir?????

**Comment by MoeMod** [comment]
https://github.com/MoeMod/CSMoE-GameDir

**Comment by choiminseongchoi** [comment]
I ment downloads
Pls

**Comment by MoeMod** [comment]
You can download .zip directly and rename csmoe to csbtem, it should work for v16.

**Comment by MoeMod** [comment]
v17 is available now, and it should work with new resource pack.
