### ISSUE TITLE
Add mods

### ISSUE THREAD

**Issue by choiminseongchoi** [MoeMod/CSMoE#37]
Zombie escape, zombie hero, 32p battle royale
You can do it
P.S. add m60 and k1a and spas 12
Pls

**Comment by MoeMod** [comment]
Zombie escape, zombie hero are coming soon... probably

**Comment by Left4Dad** [comment]
Better make zombie escape first. Its super fun

**Comment by MoeMod** [comment]
#38

**Comment by MoeMod** [comment]
Sorry for that, but Zombie Escape is deprecated.
I think that it is not fun to play ZE with bots.
