### ISSUE TITLE
Zombie bots not spawning in some maps in Zombie scenario mode. They sometimes spawns but they are stuck in one area until they stack up. Some bots (also in Zombie scenario mode) don't upgrade their health which made them easy to kill in later zombie rounds.

### ISSUE THREAD

**Issue by sledgehammer0019** [MoeMod/CSMoE#49]

**Comment by MoeMod** [comment]
1. the spawn points can be defined by either zs_spawn entities in map or csdm spawnpoint configs. Without them the server dont know how to spawn zombies.
2. Yeah... BOT dont know how to upgrade. Maybe it will be implemented in the future.

**Comment by sledgehammer0019** [comment]
Are there any way to create my own zs_spawn entity? And thanks for the reply.

**Comment by MoeMod** [comment]
> Are there any way to create my own zs_spawn entity? And thanks for the reply.

You may need to recompile the .bsp map. 
Instead, making a new CSDM spawnpoint config file must be much easier.

**Comment by sledgehammer0019** [comment]
okay man.. last question.. are there any way to create my own CSDM spawn point config file?

**Comment by MoeMod** [comment]
> okay man.. last question.. are there any way to create my own CSDM spawn point config file?

Just refer to csmoe/addons/amxmodx/configs/csdm
and you can create an CSDM spawn point config file just like those who already exists.

BTW, CSDM spawn point is supported by not only CSDM mod but ZP and other mods. 
It should be included with maps that needs random spawning.

**Comment by MoeMod** [comment]
Closed. Feel free to open another issue if you have further questions!
