### ISSUE TITLE
Zombie Scenario is too easy !!Please Fix!!

### ISSUE THREAD

**Issue by AfhamEX** [MoeMod/CSMoE#50]
The zombie is too weak. The Hp and the Damge is too WEAK!! Please make them stronger!!!

**Comment by MoeMod** [comment]
As round count increases, the speed, health, damage of zombies in ZBS will grow... 
However, unlike the ones in ZB3, we don't know the actual properties of zombies in CSO/CSNZ. We can only use some imaginary values instead.
