### ISSUE TITLE
That little purple thing at the health text.

### ISSUE THREAD

**Issue by sledgehammer0019** [MoeMod/CSMoE#54]
![Screenshot_2019-04-08-22-35-47-974_in celest xash3d csbtem](https://user-images.githubusercontent.com/47625406/56074417-cedabd80-5d66-11e9-9100-90030f6d1703.png)

**Comment by CNSRxiaodo** [comment]
Please check the game resources are the Latest .

**Comment by CNSRxiaodo** [comment]
Please check the game resources are the Latest .

**Comment by MoeMod** [comment]
there is something missing in hud.txt
please check it from the newer GameDir

**Comment by MoeMod** [comment]
closed
