### ISSUE TITLE
VGUI2 support

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#55]
We are going to make CSMoE work with ~~GoldSrc~~ VGUI2, which means a specialized client with VGUI2, GameUI, ServerBrowser just like the legacy CSBTE will be provided.
Windows only... maybe it's hard to port them.

**Comment by MoeMod** [comment]
abandoned...

**Comment by kungfulon** [comment]
Is it because of buggy input? or other issues? or it's just very hard to keep it compatible with xash3d code base?

**Comment by MoeMod** [comment]
In the latest test the tempory dialog is still invisible, however input is working.
I don't know how to fix it :(

On the other hand, we don't have enough resources to remake (possibly by reverse-engineering) all the CClientVGUI and CCounterStrikeViewPort into CS16Client right away...
It is a waste of time and efforts to produce and maintain two kinds of UI, one with touch for phones and one with vgui2 for PCs.

**Comment by MoeMod** [comment]
> Is it because of buggy input? or other issues? or it's just very hard to keep it compatible with xash3d code base?

Maybe we should give another try. I pushed a experimental branch vgui2_support, including all vgui2-releated codes grabbed from the legacy CSBTE.
It should compile and run, but no vgui2 appears. Is it the client's fault? I have tried with steam client.dll and it appears but without input.

**Comment by MoeMod** [comment]
imgui instead.
