### ISSUE TITLE
您好，给您提供的图标和背景。

### ISSUE THREAD

**Issue by SuperRock2099** [MoeMod/CSMoE#56]
链接: https://pan.baidu.com/s/1mEGfc7QlJ4aBc3AXABaUig 提取码: utj8 
我是安卓半条命吧的浪客匠心
图标是我自己做的，仿照了xash的图标元素加上cso的主图标，以及暗红色调，很突出主题
背景原本底下的半截韩文会影响美观，我用ps在上面加了一行logo进行填补，这样手机尺寸不会只出现半截字而是完全没字
一直在玩你的作品，正苦着没有贡献
望笑纳。

**Comment by MoeMod** [comment]
![IMG_1039](https://user-images.githubusercontent.com/37328384/56157270-a6b2bf00-5ff1-11e9-916c-0b2efdb41bef.PNG)

新图标已经设计好了。如果可以改进的话欢迎提出建议哦。
New icon is here. Suggestions are welcomed.

**Comment by MoeMod** [comment]
Closed.
