### ISSUE TITLE
Can you add boss battle mode?

### ISSUE THREAD

**Issue by Left4Dad** [MoeMod/CSMoE#58]
Hello, is it possible to add this mode?

Details: Please make a new gamemmode for a boss battle. Where there is only one Gigantic zombie or a big Monster or whatever it is and all humans try to kill it. If the boss killed a human,the humans dies and dont let it transform to a zombie. Make it not possible to respawn. If you can..try to make the boss huge, and has different powers, and run a little bit fast(but dont let it catch up to human easily), and make it to have alot of Hp so that it tooks 2-4 minutes of shooting to kill the boss. This is actually an exciting mode to me. So what do you think of this?

**Comment by MoeMod** [comment]
sorry for that. I don't have much time for this right now.
If someone can do this, pull requests are highly welcomed.
You can turn to those existing CS1.6 mods for this gameplay (like CSSME)

**Comment by Left4Dad** [comment]
Umm any links for Cssme?

**Comment by MoeMod** [comment]
Closed.
