### ISSUE TITLE
Mac OS can't begin new game

### ISSUE THREAD

**Issue by AndrewOculus** [MoeMod/CSMoE#60]
Can't run game on my MacBook Air . It looks like he loses some kind of dependency

![01](https://user-images.githubusercontent.com/20572113/56993732-e529ab80-6ba5-11e9-8ce4-730e3eba6396.png)
![02](https://user-images.githubusercontent.com/20572113/56993733-e529ab80-6ba5-11e9-8571-0391732dfd8f.png)
![03](https://user-images.githubusercontent.com/20572113/56993734-e529ab80-6ba5-11e9-9ae8-08eec2a59779.png)
![04](https://user-images.githubusercontent.com/20572113/56993735-e529ab80-6ba5-11e9-9135-bfdcb8b3508b.png)

**Comment by MoeMod** [comment]
1. make sure your cstrike and valve folder is complete
2. when you drag csmoe folder into the game dir, it is supposed to 'merge' rather than 'replace'. In csmoe folder should have files from both CSMoE-v19-macOS-x86_64.zip and GameDir which can be downloaded from https://github.com/MoeMod/CSMoE-GameDir

**Comment by AndrewOculus** [comment]
point 2 exactly fulfilled. so when I removed the valve and cstrike folders, nothing changed at startup, probably the problem is in them

**Comment by MoeMod** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/37328384/57009748-2912c400-6c2b-11e9-825c-4b929b07c88e.png">
There should be files like this in csmoe folder.

**Comment by MoeMod** [comment]
dlls and cl_dll from macOS package, and others from gamedir package.

**Comment by AndrewOculus** [comment]
it seem to be
![02](https://user-images.githubusercontent.com/20572113/57012745-c1e81600-6c10-11e9-9aae-05e2f806c385.png)
![01](https://user-images.githubusercontent.com/20572113/57012746-c1e81600-6c10-11e9-9802-639701f91721.png)

**Comment by MoeMod** [comment]
maybe you can try the QtLauncher.

**Comment by AndrewOculus** [comment]
You have macOS 10.13.6 installed. The program requires macOS 10.14 or later. So I have macOS High Sierra

**Comment by AndrewOculus** [comment]
So I need a fresh version of the system to run?

**Comment by MoeMod** [comment]
-game csmoe
maybe it's missing

**Comment by AndrewOculus** [comment]
so it was valve and strike folder problem, now it is all right, thank you!

**Comment by MoeMod** [comment]
Maybe next version we can bundle all those resources into .apk, .dmg or .ipa?

**Comment by MoeMod** [comment]
Seems solved.

**Comment by AndrewOculus** [comment]
Yes, nice idea, thank you!)
