### ISSUE TITLE
New iOS launcher for CSMoE

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#61]
- [x] new launch screen and UI
- [x] 3D Touch menu in springboard
- [x] tutor for newbies to copy resources
- [x] filesystem access from Files app
- [ ] ability to receive an decompress .zip or other archives to install resource packs
- [ ] start game directly from launcher and skip mainui_cpp
- [ ] customize settings
- [ ] multi language (English, Chinese Simplified and so on)
- [ ] auto update notification 
- [ ] in-game pause menu
- [ ] take over mainui_cpp

![093ECAE7FB177CD3C51834F610BB4671](https://user-images.githubusercontent.com/37328384/57246869-ead53480-7070-11e9-90e0-494ba0146915.jpg)

**Comment by MoeMod** [comment]
will be replaced by imgui.

**Comment by minecraft20042012** [comment]
link download
