### ISSUE TITLE
Weapon suggestions to be added.

### ISSUE THREAD

**Issue by Left4Dad** [MoeMod/CSMoE#66]
Can you add these weapons and grenades? 
I know that your able to add custom weapons for rifles and pistols with custom magazine and ammo. So why not add these csgo weapons? It will be fun XD

Cz75
R8 Revolver
Molotov
Negev
Tec 9
Sawed-off
Mag-7
Pp-bizon
Zeus x27
Incendiary grenade
Decoy grenade (if possible)

Tell me if its possible to do it. If u need models or need help with something else, tell me about it. I am ready to help :)

I cant help in modding and coding tho😅

**Comment by MoeMod** [comment]
😣Currently the TODO list is almost overflowed.
New features such as weapons and gameplays could be unlimited delayed...

**Comment by Left4Dad** [comment]
Oh i see XD. Its ok. But can you at least add molotov and zeus? Or you cant?

**Comment by Left4Dad** [comment]
Can?? 😅

**Comment by MoeMod** [comment]
Closed.
