### ISSUE TITLE
Command to take Skull-9?

### ISSUE THREAD

**Issue by Memefromkfv** [MoeMod/CSMoE#67]
What is the command to take the skull 9

**Comment by MoeMod** [comment]
So what's 'take' means?
The entity classname of skull9 is knife_skullaxe

**Comment by MoeMod** [comment]
CSO just uses weapon_knife and adds wrappers to make knives so that every knife is named weapon_knife.
However, my implement just adds new weapons to replace weapon_knife, but they are named knife_skullaxe, knife_zombi, etc. You can handle them by the same way as other weapons.

**Comment by Memefromkfv** [comment]
So the command like: ent_create weapon_knife_skullaxe?

**Comment by MoeMod** [comment]
ent_create knife_skullaxe

**Comment by Memefromkfv** [comment]
So how about zombie bomb? How do i can take it?

**Comment by MoeMod** [comment]
sorry that it's not implemented yet

**Comment by MoeMod** [comment]
Solved. Feel free to open another issue if you have further questions!
