### ISSUE TITLE
Bot can't use Skull-9?

### ISSUE THREAD

**Issue by Memefromkfv** [MoeMod/CSMoE#68]
Bot can't use Skull-9 why, and how do u think about that people use ur game remod it and post it on YouTube?

**Comment by MoeMod** [comment]
BOT enhancement is not completely implemented, so they are not clever enough yet.
CSMoE is an opensource and free software, modifications are not limited and pull requests are welcomed.
You are allowed to use it in uncommercial situation under GPLv3 license - to open source under GPLv3 license after modifying.

**Comment by Memefromkfv** [comment]
That all i need thank.
