### ISSUE TITLE
Command to spawn dual sword?

### ISSUE THREAD

**Issue by Memefromkfv** [MoeMod/CSMoE#72]
What is the command to spawn dual sword? And can i take dual sword in v18?.

**Comment by MouseDoktor** [comment]
ent create knife_dualsword

**Comment by MouseDoktor** [comment]
you cant spawn this weapon on v18

**Comment by Memefromkfv** [comment]
F

**Comment by Memefromkfv** [comment]
Thank doctor Mouse,♥️

**Comment by MouseDoktor** [comment]
:)

**Comment by MouseDoktor** [comment]
oh no i forgot ''_''

**Comment by MouseDoktor** [comment]
ent_create knife_dualsword

**Comment by Memefromkfv** [comment]
Yeah i know it already ex:ent_create weapon_skullaxe.

**Comment by Memefromkfv** [comment]
I mean "knife_skullaxe"

**Comment by Memefromkfv** [comment]
:)

**Comment by MoeMod** [comment]
dualsword is only available in v19 or newer versions (not available yet)

**Comment by Memefromkfv** [comment]
So when v20 will show up?

**Comment by MoeMod** [comment]
Download v21 and you will get it.
Feel free to open another issue if you have further questions!
