### ISSUE TITLE
Im waiting!!!

### ISSUE THREAD

**Issue by MouseDoktor** [MoeMod/CSMoE#73]
bro please be quick i want play v19 version

**Comment by CNSRxiaodo** [comment]
Next version is V21,and there are lots of bugs now,please wait for some time.
If you want to play it now,you can compile it yourself.

**Comment by lev24197** [comment]
I have p_ w_ v_ , sound spiert and more why i get it . I did used ent_crete weapon but invail entity why?

**Comment by CNSRxiaodo** [comment]
It just a model,we didn't add it to the CSMoE

**Comment by MoeMod** [comment]
Already released. Feel free to open another issue if you have further questions!
