### ISSUE TITLE
v19 bug

### ISSUE THREAD

**Issue by Medjed101** [MoeMod/CSMoE#74]
When I installed v19 and enter the game, screen has been in "half life" I can't play any mod, but v18 works good... but I don't have zombie mod 2 in v18.
Please help, Thanks.

**Comment by MouseDoktor** [comment]
how u downloaded v19

**Comment by MouseDoktor** [comment]
v19 is not available now

**Comment by Medjed101** [comment]
https://github.com/MoeMod/CSMoE/archive/v19.zip   This is v19 or.... im retarded 😕

**Comment by MouseDoktor** [comment]
okay bro no problem😁

**Comment by MouseDoktor** [comment]
Zombie mod 2 = Zombie mod 3

**Comment by MoeMod** [comment]
zombie mod 2 is replaced by zombie mod 3.
However you can switch to it by ` mp_gamemode zb2 `

**Comment by MoeMod** [comment]
if you are running with ios, maybe you should add ` -game csmoe ` into the launch args

**Comment by Medjed101** [comment]
Thanks
