### ISSUE TITLE
v21 not working!

### ISSUE THREAD

**Issue by MouseDoktor** [MoeMod/CSMoE#78]
crashes when I join the game and select a team please fix

**Comment by MoeMod** [comment]
Please update resource from https://github.com/MoeMod/CSMoE-GameDir

**Comment by MouseDoktor** [comment]
thanks

**Comment by lev24197** [comment]
link v21 pls

**Comment by lev24197** [comment]
how to update resource

**Comment by MoeMod** [comment]
Seems solved. Feel free to open another issue if you have further questions!
