### ISSUE TITLE
dual sword has special function yet? and if so, how to use it?

### ISSUE THREAD

**Issue by Memefromkfv** [MoeMod/CSMoE#80]
dual sword has special function yet? and if so, how to use it?

**Comment by lev24197** [comment]
thằng meme rán from fv kia

**Comment by lev24197** [comment]
mày làm video v21 chưa để tao làm

**Comment by lev24197** [comment]
mày bấm 1 lần chém thường rồi giữ chém chuột phải rồi chém thường 2 lần rồi giữ chém chuột phải là ok

**Comment by Memefromkfv** [comment]
Mày là tml nào

**Comment by Memefromkfv** [comment]
Chắc lại là tml kndragon đúng k?

**Comment by lev24197** [comment]
haha

**Comment by MoeMod** [comment]
Effects for dualsword are not available now. However, the functionality is completed. Feel free to open another issue if you have further questions!
