### ISSUE TITLE
how to add ammo or add damage weapom

### ISSUE THREAD

**Issue by lev24197** [MoeMod/CSMoE#84]
how to add ammo or add damage in csmoe
ex : m4a1 30/120 ammo changed to 100/1000

**Comment by MoeMod** [comment]
clip ammo & damage => dlls/wpn_shared/wpn_m4a1.cpp
bp ammo =>  dlls/ammo.cpp

**Comment by MoeMod** [comment]
Feel free to open another issue if you have further questions!
