### ISSUE TITLE
Weapon list for v21

### ISSUE THREAD

**Issue by Neeekoo-Chan** [MoeMod/CSMoE#91]
Can you give me the weapon list for v21 thank you 😁

**Comment by MoeMod** [comment]
You can check it here.
https://github.com/MoeMod/CSMoE/blob/master/dlls/weapons_moe_buy.cpp

**Comment by Neeekoo-Chan** [comment]
Thank You 😄 And Admin abou add more bullet or add damage weapon can you explain the easy way to edit the weapon_shared and ammo.cpp its hard to think
